### ISSUE TITLE
AdGuard changed their DNS

### ISSUE THREAD

**Issue by Celuni** [Zaczero/DNSChanger#3]
AdGuard changed their DNS.

> **IPv4**
> For "Default" servers:
> 94.140.14.14
> 94.140.15.15
> 
> For "Family protection" servers:
> 94.140.14.15
> 94.140.15.16
> 
> **IPv6**
> For "Default" servers:
> 2a10:50c0::ad1:ff
> 2a10:50c0::ad2:ff
> 
> For "Family protection" servers:
> 2a10:50c0::bad1:ff
> 2a10:50c0::bad2:ff

Source: https://adguard.com/en/adguard-dns/overview.html#instruction

**Comment by Zaczero** [comment]
@Celuni @chaintip
